# docker compose file imitating production setup
services:
  frontend:
    image: fyp24jd002/frontend:test
    build:
      target: prodtest
      context: mentalify
      dockerfile: docker/Dockerfile
      args:
        PUBLIC_URL: /projects/FYP24JD002
      #   API_URI: http://localhost:8080/api
    ports:
      - "8080:80"
