# docker compose file for local development
services:
  frontend:
    image: fyp24jd002/frontend:dev
    build:
      target: dev
      context: mentalify
      dockerfile: docker/Dockerfile
    ports:
      - "5173:5173"

  backend:
    build:
      target: dev
      context: backend
      dockerfile: docker/Dockerfile
    ports:
      - "5000:5000"
